version: "3.1"

language: en

# help recognise urls with regex
pipeline:
- name: RegexEntityExtractor
  patterns:
    - pattern: "(https?://\S+|www\.\S+)"
      name: "url"

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: FallbackClassifier
  threshold: 0.3

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
assistant_id: 20250225-150340-visible-latitude
