// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSNTI3NLUM_kCO69sgiLZbNWjy6k4tz5k',
    appId: '1:739015719802:web:ed454974dd1faf90ce74c3',
    messagingSenderId: '739015719802',
    projectId: 'grp-health-app',
    authDomain: 'grp-health-app.firebaseapp.com',
    storageBucket: 'grp-health-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCklpetClzdgl9JonFg1JwTH-dp2WiMpjE',
    appId: '1:739015719802:android:953e92974e0f6dd5ce74c3',
    messagingSenderId: '739015719802',
    projectId: 'grp-health-app',
    storageBucket: 'grp-health-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqPT-08lAr1ptT03ihZU_iuHtM6pGTJ58',
    appId: '1:739015719802:ios:b528adf9d8b81334ce74c3',
    messagingSenderId: '739015719802',
    projectId: 'grp-health-app',
    storageBucket: 'grp-health-app.firebasestorage.app',
    iosBundleId: 'com.example.team31HealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqPT-08lAr1ptT03ihZU_iuHtM6pGTJ58',
    appId: '1:739015719802:ios:b528adf9d8b81334ce74c3',
    messagingSenderId: '739015719802',
    projectId: 'grp-health-app',
    storageBucket: 'grp-health-app.firebasestorage.app',
    iosBundleId: 'com.example.team31HealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSNTI3NLUM_kCO69sgiLZbNWjy6k4tz5k',
    appId: '1:739015719802:web:7cea315fb6394062ce74c3',
    messagingSenderId: '739015719802',
    projectId: 'grp-health-app',
    authDomain: 'grp-health-app.firebaseapp.com',
    storageBucket: 'grp-health-app.firebasestorage.app',
  );
}
